
// devices

export const FETCH_DATA = 'FETCH_DATA';
export const ADD_DEVICE = 'ADD_DEVICE';
export const ADD_DEVICE_DONE = 'ADD_DEVICE_DONE';
export const REMOVE_DEVICE = 'REMOVE_DEVICE';
export const FETCH_MORE_DATA = 'FETCH_MORE_DATA';
export const REMOVE_DEVICE_DONE ='REMOVE_DEVICE_DONE'
export const DEVICES_AVAILABLE = 'DEVICES_AVAILABLE';
export const UPDATE_DEVICE_DONE='UPDATE_DEVICE_DONE';
export const UPDATE_DEVICE='UPDATE_DEVICE';
// settings
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const EXPORT_DEVICES_DONE='EXPORT_DEVICES_DONE';
export const EXPORT_DEVICES_START='EXPORT_DEVICES_START';
export const EXPORT_DEVICES_FAILED = 'EXPORT_DEVICES_FAILED';